import "./globals.css";

export const metadata = {
    title: "Primeiro App", // Define o título da página - usado para SEO do sistema
    description: "Generated by create next app", // Descrição da página - usado para SEO do sistema
};

export default function RootLayout({ children }) {
    return (
        <html lang="pt-BR">
            <body>{children}</body>
        </html>
    );
}
